//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StudentData.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studentdata
    {
        public int stuid { get; set; }
        public string stufname { get; set; }
        public string stumname { get; set; }
        public string stulname { get; set; }
        public string stuaddress { get; set; }
        public Nullable<decimal> stuphone { get; set; }
        public Nullable<System.DateTime> studob { get; set; }
        public string stucourse { get; set; }
        public Nullable<int> stuyear { get; set; }
    }
}
